#!/bin/sh

changed=0

set_opt() {
	local key=$1
	local val=$2

	if ! uci -q get "luci.$key" 2>/dev/null; then
		uci set "luci.$key=$val"
		changed=1
	fi
}

set_opt themes.Design /luci-static/design

if [ "$PKG_UPGRADE" != 1 ] && [ $changed = 1 ]; then
	set_opt main.mediaurlbase /luci-static/design
fi

set_opt themes.DesignDark /luci-static/design-dark
set_opt themes.DesignLight /luci-static/design-light

if [ $changed = 1 ]; then
	uci commit luci
fi

exit 0
