name: build-packages

on:
  workflow_dispatch:

jobs:
  build:
    name: `\({{ matrix.arch }}-\)`{{ matrix.branch }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm_cortex-a5_vfpv4
          - arm_cortex-a7_neon-vfpv4
          - arm_cortex-a8_vfpv3
          - arm_cortex-a9
          - arm_cortex-a9_vfpv3-d16
          - arm_cortex-a9_neon
          - arm_cortex-a15_neon-vfpv4
          - aarch64_cortex-a53
          - aarch64_cortex-a72
          - aarch64_cortex-a76
          - aarch64_generic
          - mips_24kc
          - mips_4kec
          - mips_mips32
          - mipsel_24kc
          - mipsel_24kc_24kf
          - mipsel_74kc
          - mipsel_mips32
          - mips64_octeonplus
          - i386_pentium4
          - x86_64
        branch:
          - openwrt-23.05
          - openwrt-24.10
          - SNAPSHOT
        exclude:
          - arch: aarch64_cortex-a76
            branch: openwrt-23.05

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: LemonCrab666/luci-theme-aurora
          # ref: main  # 尝试移除或改为 master，根据仓库实际分支调整
          # 如果私有，添加：token: ${{ secrets.GITHUB_TOKEN }} 或自定义 PAT

      - name: build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: `\({{ matrix.arch }}-\)`{{ matrix.branch }}
          PACKAGES: luci-theme-aurora
          NO_REFRESH_CHECK: true

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: aurora_`\({{ matrix.arch }}-\)`{{ matrix.branch }}
          path: bin/packages/${{ matrix.arch }}/aurora
